AllCops:
  NewCops: enable
  SuggestExtensions: false
  TargetRubyVersion: 3.2

inherit_gem:
  rubocop-ronin: rubocop.yml

#
# ronin-listener-http specific exceptions
#
Style/CaseEquality:
  Exclude:
    - 'lib/ronin/listener/http/server.rb'
